In [38]:
%matplotlib inline

import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns
sns.set(style='white')

from thinkstats2 import Pmf, Cdf, Hist

import thinkstats2
import thinkplot
from scipy.stats import linregress

In [39]:
%time house = pd.read_csv('/home/ssajjala/thads2013n.txt', sep=',', header=0)

CPU times: user 684 ms, sys: 24 ms, total: 708 ms
Wall time: 706 ms

In [40]:
house.head()

,CONTROL,AGE1,METRO3,REGION,LMED,FMR,L30,L50,L80,IPOV,...,FMTINCRELFMRCAT,FMTCOST06RELAMICAT,FMTCOST08RELAMICAT,FMTCOST12RELAMICAT,FMTCOSTMEDRELAMICAT,FMTINCRELAMICAT,FMTASSISTED,FMTBURDEN,FMTREGION,FMTSTATUS
0,'100003130103',82,'3','1',73738,956,15738,26213,40322,11067,...,'1 LTE 50% FMR','2 30 - 50% AMI','2 30 - 50% AMI','2 30 - 50% AMI','2 30 - 50% AMI','2 30 - 50% AMI','.','2 30% to 50%','-5','-5'
1,'100006110249',50,'5','3',55846,1100,17165,28604,45744,24218,...,'3 GT FMR','4 60 - 80% AMI','4 60 - 80% AMI','6 100 - 120% AMI','4 60 - 80% AMI','7 120% AMI +','.','1 Less than 30%','-5','-5'
2,'100006370140',53,'5','3',55846,1100,13750,22897,36614,15470,...,'2 50.1 - 100% FMR','4 60 - 80% AMI','5 80 - 100% AMI','6 100 - 120% AMI','4 60 - 80% AMI','4 60 - 80% AMI','.','3 50% or More','-5','-5'
3,'100006520140',67,'5','3',55846,949,13750,22897,36614,13964,...,'2 50.1 - 100% FMR','6 100 - 120% AMI','7 120% AMI +','7 120% AMI +','5 80 - 100% AMI','4 60 - 80% AMI','.','1 Less than 30%','-5','-5'
4,'100007130148',26,'1','3',60991,737,14801,24628,39421,15492,...,'3 GT FMR','3 50 - 60% AMI','3 50 - 60% AMI','3 50 - 60% AMI','3 50 - 60% AMI','7 120% AMI +','0 Not Assisted','1 Less than 30%','-5','-5'

In [41]:
house.describe()

,AGE1,LMED,FMR,L30,L50,L80,IPOV,BEDRMS,BUILT,TYPE,...,COST12RELPOVPCT,COST12RELPOVCAT,COST12RELFMRPCT,COST12RELFMRCAT,COSTMedRELAMIPCT,COSTMedRELAMICAT,COSTMedRELPOVPCT,COSTMedRELPOVCAT,COSTMedRELFMRPCT,COSTMedRELFMRCAT
count,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,...,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000,64535.000000
mean,47.968932,68109.744309,1164.395181,17712.125436,29511.032076,46207.567630,15986.664229,2.660308,1966.432835,1.065360,...,481.123050,2.574758,165.983691,2.488990,80.661251,3.770900,324.761274,2.450376,115.830454,2.328922
std,22.869374,12371.177175,394.119188,4441.564491,7407.012410,10640.616965,7219.688394,1.093778,26.304726,0.459341,...,648.790025,3.294774,168.183589,0.713639,75.058303,1.975262,375.384088,3.276692,97.841114,0.726540
min,-9.000000,38500.000000,394.000000,10257.000000,17057.000000,27307.000000,-6.000000,0.000000,1919.000000,1.000000,...,-9.000000,-9.000000,0.000000,1.000000,0.000000,1.000000,-9.000000,-9.000000,0.000000,1.000000
25%,35.000000,60300.000000,888.000000,14449.000000,24050.000000,38150.000000,12019.000000,2.000000,1950.000000,1.000000,...,155.065135,3.000000,78.760563,2.000000,43.597884,2.000000,136.580770,2.000000,67.620731,2.000000
50%,50.000000,64600.000000,1100.000000,16829.000000,28053.000000,44605.000000,15452.000000,3.000000,1970.000000,1.000000,...,308.246798,4.000000,122.699387,3.000000,64.724154,4.000000,240.498939,4.000000,97.930142,2.000000
75%,64.000000,74008.000000,1390.000000,20011.000000,33334.000000,52086.000000,18612.000000,3.000000,1985.000000,1.000000,...,596.378735,4.000000,206.979921,3.000000,95.516505,5.000000,398.416412,4.000000,137.769350,3.000000
max,93.000000,115300.000000,3511.000000,42550.000000,70850.000000,111450.000000,51635.000000,7.000000,2013.000000,9.000000,...,10336.261088,4.000000,3419.544546,3.000000,1296.983943,7.000000,6057.843858,4.000000,1928.699349,3.000000

In [42]:
list(house)
house['REGION']

0        '1'
1        '3'
2        '3'
3        '3'
4        '3'
5        '3'
6        '3'
7        '4'
8        '4'
9        '2'
10       '3'
11       '2'
12       '2'
13       '2'
14       '2'
15       '2'
16       '3'
17       '1'
18       '2'
19       '4'
20       '4'
21       '4'
22       '4'
23       '4'
24       '2'
25       '2'
26       '3'
27       '3'
28       '3'
29       '3'
        ...
64505    '1'
64506    '1'
64507    '2'
64508    '2'
64509    '1'
64510    '1'
64511    '1'
64512    '1'
64513    '1'
64514    '1'
64515    '1'
64516    '1'
64517    '4'
64518    '2'
64519    '4'
64520    '3'
64521    '3'
64522    '1'
64523    '3'
64524    '3'
64525    '4'
64526    '3'
64527    '4'
64528    '3'
64529    '1'
64530    '4'
64531    '2'
64532    '4'
64533    '4'
64534    '3'
Name: REGION, Length: 64535, dtype: object

In [47]:
def read_gss(dirname):
    """Reads GSS files from the given directory.
    
    dirname: string
    
    returns: DataFrame
    """
    dct = utils.read_stata_dict(dirname + '/GSS.dct')
    gss = dct.read_fixed_width(dirname + '/GSS.dat.gz',
                             compression='gzip')
    return gss
gss = read_gss('gss_eda')
print(gss.shape)
gss.head()

NameError: name 'utils' is not defined